### ISSUE TITLE
Pilote seul : faute ortographe  Vue exterieure = vue exterieur et probleme de taille

### ISSUE THREAD

**Issue by aldric86** [Tsht/EmptyEpsilon#1]
1. Corriger faute d'ortho
2. Possible d'avoir la taille de l'interface qui augmente (comme "tactique" ou "pilote" quand la vue exterieur n'est pas active ?

**Comment by Tsht** [comment]
1. Ortographe ok
2. Bug lors de la première apparition de l'écran, l'interface ne prend pas tout l'écran

**Comment by Tsht** [comment]
Résolu avec le commit https://github.com/Tsht/EmptyEpsilon/commit/c11d126ff2e2c1d9ac88a26dff0937183b7ec9a8
