### ISSUE TITLE
CIC : lecture du combat - enlever les arcs de tir pour les chasseurs

### ISSUE THREAD

**Issue by Cyvern2182** [Tsht/EmptyEpsilon#101]
les arcs de tirs des chasseurs rendent le combat difficile a lire pour l'artilleur et les autres joueurs. serait t'il possible qu'il n'apparaissent pas a l'écran?

**Comment by Cyvern2182** [comment]
potentiellement a généraliser sur toutes les escardres du CIC

**Comment by Cyvern2182** [comment]
revue lecture de jeu:

on me reporte que cette issue est la plus importante a  résoudre pour les PJ, la lecture de jeu n'est pas bonne

on me demande si c'est possible de ne voir les arcs laser Uniquement du vaisseau PJ et que pour l'artilleur?

**Comment by Tsht** [comment]
commit 471c084
