### ISSUE TITLE
CIC (nice to have) - option de pouvoir centrer la vue sur une escadrille en particulier -- ou de délocker la caméra du vaisseau

### ISSUE THREAD

**Issue by Cyvern2182** [Tsht/EmptyEpsilon#102]
serait t'il difficile de pouvoir centrer le radar sur une escadrille? ou alternativement de pouvoir délocker la caméra en vue CIC pour pouvoir suivre le combat si le vaisseau s'en éloignr?

**Comment by Cyvern2182** [comment]
d'apres ce que j'ai compris, le joueur a un souci quand la flotte sors de sa portée radar

ce serait plutot un probleme de camera, soit suivre son escadrille en effet soit pouvoir bouger la caméra hors du champs du vaisseau (dans une certaines mesure)

**Comment by Cyvern2182** [comment]
mais je n'étais pas au courant / avait oublié sur le clic droit sur le nom, je lui communique ça demain soir et je te réponds si ça lui suffit

**Comment by Tsht** [comment]
Clic gauche :) Sur le nom de la flotte sur la droite.

**Comment by Cyvern2182** [comment]
j'ai vu ça, j'y arrive donc je vais lui expliquer plus en détails
