### ISSUE TITLE
Equilibrage / simplification drone master

### ISSUE THREAD

**Issue by aldric86** [Tsht/EmptyEpsilon#2]
Code à voir  
1. Garder les baies d'envol 
2. mixer energie/missile/thermique / reparation  : baie maintenance (autoregeneration energie/autoreparation/ autorefill missile (sans limite de stock ) / reduction termique automatique 
3. Ajouter 4 emplacement stocks 
4. Accelerer le temps de transfert ( -50% du temps) 

![image](https://user-images.githubusercontent.com/60329759/91647044-586f5600-ea56-11ea-869d-25a2faa25044.png)

**Comment by Tsht** [comment]
Propositions de quick fixes :
- La baie "Reparation"  fait aussi l'energie et le thermique (en attendant mieux ; une baie special "maintenance" tout en un)
- Les missiles sont recharges a chaque atterrissage
