### ISSUE TITLE
Pilote seul hangar ( chasseur ) - Barre rouge sur l'UI

### ISSUE THREAD

**Issue by aldric86** [Tsht/EmptyEpsilon#56]
2. Quand pas d'energie dans la fregate barre rouge permanente 
![image](https://user-images.githubusercontent.com/60329759/108607847-329e8a80-73c3-11eb-8a0c-f93c2fc6741a.png)

**Comment by Tsht** [comment]
Besoin d'un scénario pour reproduire

**Comment by Tsht** [comment]
Duplicata de #63 issues/63
