### ISSUE TITLE
Ajout bouton "saut d'urgence" 

### ISSUE THREAD

**Issue by aldric86** [Tsht/EmptyEpsilon#64]
Condition
- Vaisseau PJ 
- Moteur jump sur le vaisseau et 50% ou plus d'état

Effet : 
Consomme :
- Timer de saut au moins 10 secondes (si possible - optionnel ) 
- 25% de la capacité de reparation max en moins. à chaque saut d'urgence (100-75-50-25-0) 
- 25% dégats systems sur tout les systemes du vaisseau  (sur le niveau max) 

  - teleport vaisseau PJ sur  setPosition(-82713, -5198984)  (position warp non relative pareil sur toute les cartes) 
  
  HUD 
Bouton à coté ou en dessous de "saut"  ou case à cocher puis saut

![image](https://user-images.githubusercontent.com/60329759/118511645-6541f000-b732-11eb-9ac2-832ecabd97e3.png)

**Comment by Tsht** [comment]
Pas sûr d'avoir compris 50% d'état, c'est quoi l'état exactement ici ? Hull ? Energie ? Dégâts sur tous les systèmes ?

**Comment by aldric86** [comment]
> 
> 
> Pas sûr d'avoir compris 50% d'état, c'est quoi l'état exactement ici ? Hull ? Energie ? Dégâts sur tous les systèmes ?


Etat du systeme moteur de saut jump

**Comment by Tsht** [comment]
Version 4.0.2
