### ISSUE TITLE
Empecher les probes/sonde d'exploser les mines

### ISSUE THREAD

**Issue by aldric86** [Tsht/EmptyEpsilon#66]
les sondes ne doivent pas pouvoir activer les mines

**Comment by Tsht** [comment]
Il faudrait surtout que les sondes ne soient pas infinies.

**Comment by aldric86** [comment]
Les sondes sont limité à 16 de base ( peut etre reduit ) mais sont trés utiliser pour l'exploration. Elles ne sont pas infini sauf si le vaisseau est docké à une station qui en donne. 

L'explosion des mines par des sondes rendent le deminage trivial. 
2. options : Corriger (pas d'explosion mine par sonde) OU reduire le nombre de sonde mais dans ce cas ca privera de moyen de reco le vaisseau PJ

**Comment by Tsht** [comment]
C'est clos et suivi par une autre issue, merci de ne pas réouvrir.
