### ISSUE TITLE
CIC : Controle depuis un vaisseau pour envoyer des escadres de petit vaisseau type chasseur ou bombardier en IA 

### ISSUE THREAD

**Issue by aldric86** [Tsht/EmptyEpsilon#76]
Création d'un nouveau poste pour generer et envoyer des vaisseaux (peut etre reutiliser le hangar) qui spawn soit seul soit en escadre (par exemple 4 chasseur + 1 leader , cf script de carte pour MJ pour faire apparaitre des escadres coherentes

donnez des ordres d'attaque et de mouvement à ses escadres

systeme de réapprovisionnement des escadres via docking à une station ou par action MJ tweak

**Comment by Tsht** [comment]
Reste : 
-Ecran MJ
-Réapprovisionnement (?)
-Bloquer zoom out
-Virer le code de sélection qui sert à rien dans cicscreen
-Debugger le pointer null
-Mettre les fonctions scriptables 
-Si y'a tous les vaisseaux (au moins), ne pas virer l'escadre 
-Bouton pour declutter l'interface temporairement (hide)

**Comment by Tsht** [comment]
Nouveau point : une vaisseau ennemi qui attaque un chasseur de l'escadrille ne passe pas en rouge.
