### ISSUE TITLE
CIC : crash lié a l'interface CIC

### ISSUE THREAD

**Issue by Cyvern2182** [Tsht/EmptyEpsilon#97]
sur l'interface CIC, si je n'ai pas d'escadrille en vol, je crash quand j'essaie de cliquer droit "a travers" certains boutons de l'interface 

de la meme façon, si je fait un carré de séléctions alors qu'il n'y a pas d'escouade en l'air, ça plante

**Comment by Cyvern2182** [comment]
apres test plus spécifiques, cliquer gauche ou droit n'importe ou dans le vide fait crasher le client

**Comment by Tsht** [comment]
corrigé par ce commit : f6690d28fecf21d998dcf4643ca4b859f86349ab
