### ISSUE TITLE
impossible de réparer le CIC apres dégats systemes

### ISSUE THREAD

**Issue by Cyvern2182** [Tsht/EmptyEpsilon#99]
le CIC n'apparait pas dans les systemes coté maitre des réacteur et MJ spatial, ce qui fait qu'on ne peut pas réparer ce systeme ni coté  joueur ni par intervention MJ

**Comment by Tsht** [comment]
Est-ce que tu as mis au moins un dock sur le vaisseau (avec setDocks) ? J'ai l'impression que la visibilité du system hangar y est conditionnée.

**Comment by Cyvern2182** [comment]
j'ai mis un set docks, le systeme apparait, je vois demain avec les pj pour test en conditions réelles. 
j'ai en tete de regarder ce que ça donne niveau conso energie? est ce que le jeu traite ça comme un "nouveau" systeme et alourdis la charge en termes d'énergie ou est ce que ça comptait déja, de maniere cachée ?
